name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: maven

      - name: Build and test
        run: mvn clean install

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/

      - name: Package JAR
        run: mvn package -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: store-management-tool-jar
          path: target/*.jar

      - name: Build Docker image
        run: |
          docker build -t store-management-tool:latest .
          docker images

      - name: Verify Docker image exists
        run: docker image inspect store-management-tool:latest

      - name: Save Docker image as artifact
        run: docker save -o store-management-tool.tar store-management-tool:latest

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: store-management-tool.tar
